Numerous fixes
- Find only completed builds using a single call to jq instead of two calls and awk.
 - Prefix output with [sync-ports]
 - Properly autodetct the pkg jail for 10.2

diff --git a/sync-ports b/sync-ports
--- a/sync-ports
+++ b/sync-ports
@@ -1,5 +1,5 @@
 #!/bin/sh
-# Copyright (c) 2014-2015 Reed A. Cartwright <cartwright@asu.edu>
+# Copyright (c) 2014-2016 Reed A. Cartwright <reed@cartwrig.ht>
 # Copyright (c) 2014-2015 Alberto Villa <avilla@FreeBSD.org>
 # Copyright (c) 2015 Mike Clarke <jmc-freebsd2@milibyte.co.uk>
 #
@@ -26,11 +26,14 @@ PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin
 # Determine PKG_JAIL
 case `uname -r` in
 *CURRENT) : ${PKG_JAIL:=head-`uname -m`-default} ;;
+10.*)     : ${PKG_JAIL:=101`uname -m`-default} ;;
+9.*)      : ${PKG_JAIL:=93`uname -m`-default} ;;
+8.*)      : ${PKG_JAIL:=84`uname -m`-default} ;;
 *)        : ${PKG_JAIL:=`uname -r | cut -d- -f1 | tr -d .``uname -m`-default} ;;
 esac
 
 # Determine PKG_SERVER
-if [ -z "${PKG_SERVER}" ]; then
+if [ -z "${PKG_URL}" -a -z "${PKG_SERVER}" ]; then
 	case "${PKG_JAIL}" in
 	93i386-default)     PKG_SERVER=beefy1.isc.freebsd.org ;;
 	101i386-quarterly)  PKG_SERVER=beefy1.isc.freebsd.org ;;
@@ -44,7 +47,7 @@ if [ -z "${PKG_SERVER}" ]; then
 	84i386-default)     PKG_SERVER=beefy5.nyi.freebsd.org ;;
 	101amd64-default)   PKG_SERVER=beefy6.nyi.freebsd.org ;;
 	84amd64-default)    PKG_SERVER=beefy6.nyi.freebsd.org ;;
-	*)	>&2 echo "ERROR: Unable to determine package server for ${PKG_JAIL}."
+	*)	>&2 echo "[sync-ports] ERROR: Unable to determine package server for ${PKG_JAIL}."
 		exit 1
 		;;
 	esac
@@ -74,31 +77,29 @@ fi
 # Fetch data from server
 JSON=`fetch -qo - "${PKG_URL}"`
 if [ $? -ne 0 ]; then
-	>&2 echo "ERROR: Unable to fetch data from package server."
+	>&2 echo "[sync-ports] ERROR: Unable to fetch data from package server."
 	exit 1
 fi
 
 # Parse revision information from server (exclude incomplete builds)
-REV=`printf %s "${JSON}" | jq -c '.builds[]' |
-	awk '/status":"stopped[^"]+done/ { build = $0 }; END { print build }' |
-	jq -r '.svn_url | split("@")[1]'`
+REV=`printf %s "${JSON}" | jq -r '[.builds[] | select(.status? == "stopped:done:") | .buildname] | max'`
 
 # Check revision information
 if expr "${REV}" : '^[[:digit:]][[:digit:]]*$' >/dev/null; then
 	# Skip update if revisions are in sync
 	CURREV=`svnlite info "${PORTSDIR}" | awk -F': ' '$1 == "Revision" {print $2; exit}'`
 	if [ -z "${CURREV}" ]; then
-		>&2 echo "ERROR: Unable to get current revision for ports tree '${PORTSTREE}'."
+		>&2 echo "[sync-ports] ERROR: Unable to get current revision for ports tree '${PORTSTREE}'."
 		exit 1
 	fi
 	if [ "${CURREV}" -ne "${REV}" ]; then
-		echo "====>> Updating ports tree '${PORTSTREE}' from revision ${CURREV} to ${REV}"
+		echo "[sync-ports] Updating ports tree '${PORTSTREE}' from revision ${CURREV} to ${REV}"
 		svnlite up -q -r "${REV}" "${PORTSDIR}"
 	else
-		echo "====>> Ports tree '${PORTSTREE}' is up to date at revision ${CURREV}"
+		echo "[sync-ports] Ports tree '${PORTSTREE}' is up to date at revision ${CURREV}"
 	fi
 	exit
 else
-	>& echo "ERROR: Unable to determine revision number for latest packages."
+	>& echo "[sync-ports] ERROR: Unable to determine revision number for latest packages."
 	exit 1
 fi
